### ISSUE TITLE
Add dates for garbage collection to calendar

### ISSUE THREAD

**Issue by ebartz** [ebartz/home-automation#2]
The Dates can be parsed from http://213.168.213.236/bremereb/bify/bify.jsp?strasse=xxxx&hausnummer=0815

**Comment by stefanriegel** [comment]
with a nice Icon for each garbage bag! :dancers:

**Comment by ebartz** [comment]
Has been added to the dasboard with 26638899a0606e5c91623fda6c8df8e97fc50023
